#!/bin/bash
# To enable the script, execute: chmod +x sct

app() {
    poetry run streamlit run soundcloud_tools/streamlit/app.py
}

weekly() {
    poetry run soundcloud_tools "$@"
}

# Call functions based on command line arguments
"$@"
